version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  publish:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish
  test:
    docker:
      - image: rishabhpoddar/supertokens_website_sdk_testing
    steps:
      - checkout
      - run: exit 1
      - slack/status

workflows:
  version: 2
  tagged-build:
    jobs:
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test:
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
